name: Trigger Prefect
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  trigger-prefect:
    runs-on: ubuntu-latest
    steps:
      - name: Install Prefect client
        run: pip install prefect
      - name: Start deployment run
        env:
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
          PREFECT_API_AUTH_STRING: ${{ secrets.PREFECT_API_AUTH_STRING }}

          DATA_REPOSITORY: ${{ vars.DATA_REPOSITORY }}
          PIPELINE_SETTINGS: ${{ vars.PIPELINE_SETTINGS }}
        run: |
          prefect deployment run "new-training-and-evaluation/new-local-training" \
          --param code_repo_url="https://github.com/${GITHUB_REPOSITORY}.git" \
          --param dataset_repo_url="${DATA_REPOSITORY}" \
          --param settings="${PIPELINE_SETTINGS}"